feature(TUP-28405) Collect hardware info.
Talend/tcommon-studio-se pull request #3627
Opened 2020-09-10 02:06 UTC by sbliu

https://jira.talendforge.org/browse/TUP-28405

2020-09-14 02:20 UTC, jding-tlnd commented
Approved, please merge after the 731 temp patch test ok

2020-09-14 02:20 UTC, jding-tlnd approved these changes

2020-09-14 02:59 UTC, nrousseau requested changes
measure to be done in another thread
slf4j-api jar to be removed (it's already in the platform / as bundle)

2020-09-14 10:47 UTC, nrousseau submitted a review, later dismissed

2020-09-17 06:35 UTC, wchen-talend approved these changes

2020-09-17 06:37 UTC, merged