fix(TBD-12384): fix Impala version for CDP
Talend/tcommon-studio-se pull request #4207
Opened 2021-04-14 15:20 UTC by AlixMetivier

2021-04-14 15:31 UTC, sponomarova approved these changes

2021-04-15 07:19 UTC, Redwene requested changes
there is some warning to remove for using impala driver from impala component.

2021-04-15 08:08 UTC, Redwene approved these changes
LGTM

2021-04-19 09:39 UTC, cbadillo1603 approved these changes
reviewed

2021-05-12 13:13 UTC, closed without merging