Jzhang/tup 32554 of
Talend/tcommon-studio-se pull request #4529
Opened 2021-08-20 06:50 UTC by jiezhang-tlnd

2021-08-30 04:10 UTC, wchen-talend commented on main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ActionBarBuildHelper.java
> +        if (PluginChecker.isTIS()) {
OEM product won't have feature manager also .

2021-08-30 08:05 UTC, cmeng-talend requested changes
please move the feature management related things into featmanage.ui plugin

2021-08-30 08:05 UTC, cmeng-talend commented on main/plugins/org.talend.rcp/META-INF/MANIFEST.MF
> + org.talend.studiolite.p2.featmanage.ui
it's better to remove the requirement of org.talend.studiolite.p2.featmanage.ui

2021-09-06 09:19 UTC, cmeng-talend approved these changes

2021-09-15 08:09 UTC, wchen-talend approved these changes

2021-09-15 08:09 UTC, merged