fix(TDI-48676):ResumeUtil OOM
Talend/tcommon-studio-se pull request #5709
Opened 2022-10-17 13:17 UTC by pyzhou-talend

https://jira.talendforge.org/browse/TDI-48676

2022-10-18 02:29 UTC, wwang-talend commented on main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
> +            if (content.length() > 2 << 18) { //2M
2 << 18 appear 4 times, please remove the duplicate

2022-10-18 02:31 UTC, wwang-talend commented on main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
> +                    final String substring = content.substring(index, index + (2 << 18));
this will make lots of base 2M size memory middle size string, though not at the same time point, but make lots of press on jvm gc. Advice to use String.charAt method to read directly to avoid to make new array in background.

2022-10-18 02:52 UTC, wwang-talend requested changes

2022-10-18 02:52 UTC, wwang-talend commented on main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
> +                    final String substring = content.substring(index, index + (2 << 18));
public CharBuffer put(String src, int start, int end) api can help this

2022-10-18 03:32 UTC, pyzhou-talend commented on main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
> +                    final String substring = content.substring(index, index + (2 << 18));
I cannot use Charbuffer here. As I'm using FileChannel to write the content to the log file. It requires the ByteBuffer (As the file needs encoding). 
First, this is an edge case, rere user will have large contexts like hundreds of MB.
Second, the substring should be recollected in Eden in GC, the GC in Eden is quite effective.

2022-10-18 03:32 UTC, pyzhou-talend commented on main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
> +            if (content.length() > 2 << 18) { //2M
I will change that

2022-10-19 02:52 UTC, wwang-talend approved these changes

2022-10-27 06:51 UTC, merged