fix(TUP-37349)Data viewer for tCouchBaseInput get npe error
Talend/tcommon-studio-se pull request #5848
Opened 2022-12-02 03:09 UTC by jiezhang-tlnd

https://jira.talendforge.org/browse/TUP-37349

2023-01-03 06:07 UTC, wwang-talend approved these changes

2023-01-09 07:07 UTC, cmeng-talend requested changes

2023-01-09 07:07 UTC, cmeng-talend commented on main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
> +                if (StringUtils.equals(name, param.getName())) {
The original null issue is not fixed

2023-01-31 03:05 UTC, cmeng-talend approved these changes

2023-02-06 01:39 UTC, merged